services:
  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin1234
      MARIADB_DATABASE: ProjetoExpoeetepaBD
      MARIADB_USER: joao-admin
      MARIADB_PASSWORD: joao-admin1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal

  tomcat-arduino:
    image: tomcat:9-jdk21
    container_name: tomcat-arduino
    ports:
      - "8081:8080"
    volumes:
      - ./arduino-app/ArduinoApp.war:/usr/local/tomcat/webapps/ArduinoApp.war
    restart: always
    networks:
      - internal
    depends_on:
      - mariadb

  tomcat-web:
    image: tomcat:9-jdk21
    container_name: tomcat-web
    ports:
      - "8082:8080"
    volumes:
      - ./web-app/WebApp.war:/usr/local/tomcat/webapps/WebApp.war
    restart: always
    networks:
      - internal
    depends_on:
      - mariadb

networks:
  internal:
    driver: bridge

volumes:
  mariadb_data:

